name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: 7.4
            MAGENTO_VERSION: 2.4.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create reverse proxy network
        run: docker network create backend

      - name: Run reverse proxy network
        run: docker run -d --net backend -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

      - name: Setup database
        run: docker run -d --net backend --name mariadb -e MARIADB_USER=magento -e MARIADB_PASSWORD=magento -e MARIADB_ROOT_PASSWORD=root -e MARIADB_DATABASE=magento mariadb:10.4

      - name: Setup elasticsearch
        run: docker run -d -m 512m --name elasticsearch --net backend -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.16.2

      - name: Run docker image
        run: VIRTUAL_HOST=magento2.test.com DB_SERVER=mariadb ELASTICSEARCH_SERVER=elasticsearch MAGENTO_HOST=magento2.test.com docker-compose -f .github/workflows/templates/docker-compose.yml up -d

      #- name: Create branch for Composer
      #  run: git checkout -b continuous-integration-test-branch

      - name: Upload the code into the docker container
        run: docker exec magento2-container composer require Adyen/adyen-magento2

      - name: Enable developer mode
        run: docker exec magento2-container php bin/magento deploy:mode:set developer

      - name: Run tests
        run: docker exec magento2-container bash -c "cd /data/dev/tests/integration/ && /data/vendor/bin/phpunit -c /data/dev/tests/integration/phpunit.xml"
