name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: 7.4
            MAGENTO_VERSION: 2.4.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create docker image
        run: docker-compose -f .github/workflows/templates/docker-compose.yml up -d

      # Temp solution to wait for install script to run
      - name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'

      #- name: Create branch for Composer
      #  run: git checkout -b continuous-integration-test-branch

      - name: Upload the code into the docker container
        run: docker exec magento2-container composer require adyen/module-payment:dev-feature/graphql-reapply

      - name: Enable developer mode
        run: docker exec magento2-container php bin/magento deploy:mode:set developer

      - name: Run tests
        run: docker exec magento2-container bash -c "cd /var/www/html/ && vendor/bin/phpunit -c vendor/adyen/module-payment/Test"

      #docker exec magento2-container bash -c "cd /var/www/html/ && vendor/bin/phpunit --configuration vendor/adyen/module-payment/Test/api-functional/phpunit_graphql.xml --testsuite vendor/adyen/module-payment/Test/api-functional/GraphQl"
