name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: 7.4
            MAGENTO_VERSION: 2.4.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create docker image
        run: docker-compose -f .github/workflows/templates/docker-compose.yml up -d

      - name: Show running containers
        run: docker container ls --all

      #- name: Create branch for Composer
      #  run: git checkout -b continuous-integration-test-branch

      - name: Upload the code into the docker container
        run: docker exec magento2-container composer require Adyen/adyen-magento2

      - name: Enable developer mode
        run: docker exec magento2-container php bin/magento deploy:mode:set developer

      - name: Run tests
        run: docker exec magento2-container bash -c "cd /data/dev/tests/integration/ && /data/vendor/bin/phpunit -c /data/dev/tests/integration/phpunit.xml"
